# -*- coding: utf-8 -*-

RED_ROOK = 1
RED_KNIGHT = 2
RED_ELEPHANT = 3
RED_MANDARIN = 4
RED_CANNON = 5
RED_PAWN = 6
RED_KING = 7
BLACK_ROOK = 11
BLACK_KNIGHT = 12
BLACK_ELEPHANT = 13
BLACK_MANDARIN = 14
BLACK_CANNON = 15
BLACK_PAWN = 16
BLACK_KING = 17
BLACK_RED_LINE = 10
